# Generated by Django 5.0.7 on 2024-12-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0002_adminapps_remove_myusers_name_myusers_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapps',
            name='app_icon',
            field=models.ImageField(null=True, upload_to='app_icons/'),
        ),
        migrations.AlterField(
            model_name='adminapps',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
