# Generated by Django 5.0.7 on 2024-12-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0004_alter_userprofile_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
