# Generated by Django 5.0.7 on 2024-12-25 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0005_alter_userprofile_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
