# Generated by Django 5.0.7 on 2024-12-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapps',
            name='app_icon',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='userappdownload',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_apps', to='mytask.adminapps'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_of_task_completed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
