# Generated by Django 5.0.7 on 2024-12-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0008_alter_adminapps_app_icon_alter_userappdownload_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappdownload',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
