# Generated by Django 5.0.7 on 2024-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0009_userappdownload_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapps',
            name='app_icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
